language: sh
cache: apt
env:
  - LINT=true
  - SHELL=bash
  - SHELL=dash
  - SHELL=ksh
  - SHELL=zsh
  - SHELL=bash NON_ENGLISH=true LC_ALL=fr_FR.UTF-8
matrix:
  fast_finish: true
  include:
    - env:
        - SHELL=bash
      os: osx
script:
  - |
    if [ -n "${LINT}" ]; then
      shellcheck --version
      shellcheck -s sh bin/shpec  # 'sh' refers to POSIX
    else
      $SHELL bin/shpec
    fi
before_install:
  - |
    install_shell() {
      echo "Installing $SHELL"
      sudo apt-get update -qq
      sudo apt-get install -y $SHELL
    }
    install_language_pack() {
      echo "Installing language pack"
      sudo apt-get --reinstall install -qq language-pack-fr
    }

    if [ "${SHELL}" = "zsh" ]; then
      echo "disable -r end; setopt sh_word_split" >> $HOME/.zshenv
    fi

    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ -n "${NON_ENGLISH}" ]; then
        install_language_pack
      fi

      if ! type $SHELL > /dev/null; then
        install_shell
      fi
    fi
